server:
  port: 8080   # HTTP (Tomcat) port
  context-path: /springboot-oidc-openam

openam:
  client:
    clientId: OAuth2Agent
    clientSecret: password
    accessTokenUri: http://openam.example.com:9000/openam/oauth2/access_token
    userAuthorizationUri: http://openam.example.com:9000/openam/oauth2/authorize
    tokenName: access_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: openid email profile
  resource:
    userInfoUri: http://openam.example.com:9000/openam/oauth2/userinfo

logging:
  level:
    org.springframework.security: DEBUG